"""Add buy_price and sell_price to Trade model

Revision ID: 416710dea61a
Revises: 
Create Date: 2025-07-15 11:00:22.603814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '416710dea61a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('buy_price', sa.Numeric(10, 2), nullable=True))
    op.add_column('trades', sa.Column('sell_price', sa.Numeric(10, 2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'buy_price')
    op.drop_column('trades', 'sell_price')
    # ### end Alembic commands ###
