"""Add user plan and AI insights tables

Revision ID: ec3ab21c0f7e
Revises: fe2f213c7e70
Create Date: 2025-08-05 14:29:17.973302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3ab21c0f7e'
down_revision = 'fe2f213c7e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_ai_insights_date', sa.DateTime(), nullable=True))

    # Create AIInsights table
    op.create_table('ai_insights',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('insights_data', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop AIInsights table
    op.drop_table('ai_insights')
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_ai_insights_date')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
